classdef DiffusionEvolution < ALGORITHM
% <2025> <multi> <real> <constrained/none>
% Diffusion Evolution - A hybrid algorithm combining diffusion models with evolutionary algorithms
% for multi-objective optimization
%
% This algorithm integrates diffusion models as intelligent mutation operators within the
% evolutionary framework. The diffusion model learns the distribution of current population
% and generates high-quality offspring to accelerate convergence.
%
%------------------------------- Parameters --------------------------------
% N              - Population size (default: 100)
% diffusion_steps- Number of diffusion steps (default: 1000)
% sample_size    - Number of samples generated by diffusion per generation (default: 50)
% hybrid_rate    - Proportion of diffusion-generated offspring (default: 0.3)
% model_type     - Type of diffusion model ('DDPM' or 'DDIM') (default: 'DDPM')
% training_epochs- Epochs for training diffusion model per generation (default: 10)
% noise_schedule - Noise schedule type ('linear' or 'cosine') (default: 'linear')
% condition_type - Condition type for diffusion ('none', 'fitness', 'rank') (default: 'fitness')
%
%------------------------------- Reference --------------------------------
% Inspired by diffusion models in deep learning and evolutionary computation.
% This implementation combines the strengths of both approaches for multi-objective optimization.
%
%------------------------------- Copyright --------------------------------
% Copyright (c) 2025. This implementation is based on PlatEMO framework.
% All publications which use this platform or any code in the platform should
% acknowledge the use of "PlatEMO" and reference "Ye Tian, Ran Cheng, Xingyi Zhang,
% and Yaochu Jin, PlatEMO: A MATLAB platform for evolutionary multi-objective optimization
% [educational forum], IEEE Computational Intelligence Magazine, 2017, 12(4): 73-87".
%--------------------------------------------------------------------------

properties (Access = private)
    diffusionModel      % Diffusion model instance
    noiseSchedule       % Noise schedule for diffusion
    trainingData        % Historical training data for diffusion model
    scaler              % Data scaler for normalization
    generationCount     % Current generation counter
    bestIndividuals     % Best individuals for conditional generation
end

methods
    function main(Algorithm, Problem)
        %% Initialize parameters
        [N, diffusionSteps, sampleSize, hybridRate, modelType, trainingEpochs, noiseSchedule, conditionType] = ...
            Algorithm.ParameterSet(100, 1000, 50, 0.3, 'DDPM', 10, 'linear', 'fitness');
        
        %% Initialize population
        Population = Problem.Initialization();
        Algorithm.generationCount = 0;
        Algorithm.trainingData = [];
        Algorithm.bestIndividuals = [];
        
        %% Initialize diffusion model components
        Algorithm.initializeDiffusionModel(Problem, diffusionSteps, noiseSchedule);
        
        %% Main optimization loop
        while Algorithm.NotTerminated(Population)
            Algorithm.generationCount = Algorithm.generationCount + 1;
            
            %% Train diffusion model on current population
            if Algorithm.generationCount > 1 || length(Algorithm.trainingData) > 0
                Algorithm.trainDiffusionModel(Population, Problem, trainingEpochs, conditionType);
            end
            
            %% Generate offspring using hybrid strategy
            Offspring = Algorithm.generateOffspring(Population, Problem, N, sampleSize, hybridRate, conditionType);
            
            %% Environmental selection
            Population = Algorithm.environmentalSelection([Population; Offspring], N, Problem);
            
            %% Update training data
            Algorithm.updateTrainingData(Population, Problem);
        end
    end
end

methods (Access = private)
    
    function initializeDiffusionModel(Algorithm, Problem, diffusionSteps, noiseSchedule)
        % Initialize diffusion model components
        Algorithm.noiseSchedule = Algorithm.createNoiseSchedule(diffusionSteps, noiseSchedule);
        Algorithm.scaler = Algorithm.initializeScaler(Problem);
        Algorithm.diffusionModel = Algorithm.createDiffusionModel(Problem);
    end
    
    function noiseSchedule = createNoiseSchedule(Algorithm, timesteps, scheduleType)
        % Create noise schedule for diffusion process
        if strcmp(scheduleType, 'linear')
            beta_start = 0.0001;
            beta_end = 0.02;
            noiseSchedule = linspace(beta_start, beta_end, timesteps);
        elseif strcmp(scheduleType, 'cosine')
            s = 0.008;
            steps = linspace(0, timesteps, timesteps + 1);
            ft = cos((steps ./ timesteps + s) ./ (1 + s) * pi / 2).^2;
            alphas_cumprod = ft ./ ft(1);
            betas = 1 - (alphas_cumprod(2:end) ./ alphas_cumprod(1:end-1));
            noiseSchedule = min(betas, 0.999);
        else
            error('Unknown noise schedule type: %s', scheduleType);
        end
    end
    
    function scaler = initializeScaler(Algorithm, Problem)
        % Initialize data scaler based on problem bounds
        scaler.lower = Problem.lower;
        scaler.upper = Problem.upper;
        scaler.range = Problem.upper - Problem.lower;
    end
    
    function diffusionModel = createDiffusionModel(Algorithm, Problem)
        % Create diffusion model structure
        diffusionModel = struct();
        diffusionModel.timesteps = length(Algorithm.noiseSchedule);
        diffusionModel.alpha = 1 - Algorithm.noiseSchedule;
        diffusionModel.alphaHat = cumprod(diffusionModel.alpha);
        diffusionModel.sqrtAlphaHat = sqrt(diffusionModel.alphaHat);
        diffusionModel.sqrtOneMinusAlphaHat = sqrt(1 - diffusionModel.alphaHat);
        
        % Precompute reverse process parameters
        diffusionModel.alphaHatPrev = [1, diffusionModel.alphaHat(1:end-1)];
        diffusionModel.posteriorVariance = Algorithm.noiseSchedule .* (1 - diffusionModel.alphaHatPrev) ./ (1 - diffusionModel.alphaHat);
        
        % Model parameters (simplified neural network equivalent)
        diffusionModel.weights = randn(Problem.D, Problem.D) * 0.1;
        diffusionModel.bias = zeros(1, Problem.D);
        
        % Training history
        diffusionModel.trainingLoss = [];
    end
    
    function trainDiffusionModel(Algorithm, Population, Problem, trainingEpochs, conditionType)
        % Train diffusion model on current population
        if length(Population) < 10
            return; % Not enough data for training
        end
        
        % Prepare training data
        [trainingData, conditions] = Algorithm.prepareTrainingData(Population, Problem, conditionType);
        
        % Store training data
        Algorithm.trainingData = [Algorithm.trainingData; trainingData];
        if length(Algorithm.trainingData) > 1000
            Algorithm.trainingData = Algorithm.trainingData(end-999:end, :);
        end
        
        % Simplified training loop (equivalent to neural network training)
        for epoch = 1:trainingEpochs
            loss = Algorithm.diffusionTrainingStep(trainingData, conditions);
            Algorithm.diffusionModel.trainingLoss(end+1) = loss;
        end
    end
    
    function [trainingData, conditions] = prepareTrainingData(Algorithm, Population, Problem, conditionType)
        % Prepare training data from population
        n = length(Population);
        trainingData = zeros(n, Problem.D);
        
        for i = 1:n
            trainingData(i, :) = Algorithm.normalize(Population(i).decision, Algorithm.scaler);
        end
        
        % Prepare conditions based on condition type
        if strcmp(conditionType, 'none')
            conditions = [];
        elseif strcmp(conditionType, 'fitness')
            conditions = [Population.objs];
        elseif strcmp(conditionType, 'rank')
            % Calculate ranks based on non-dominated sorting
            [~, rank] = EnvironmentalSelection(Population, length(Population));
            conditions = rank / max(rank); % Normalize to [0,1]
        else
            conditions = [];
        end
    end
    
    function loss = diffusionTrainingStep(Algorithm, trainingData, conditions)
        % Single training step for diffusion model
        n = size(trainingData, 1);
        batchSize = min(32, n);
        
        % Sample batch
        idx = randi(n, batchSize, 1);
        x0 = trainingData(idx, :);
        
        % Sample timesteps
        t = randi([1, length(Algorithm.noiseSchedule)], batchSize, 1);
        
        % Add noise (forward process)
        noise = randn(size(x0));
        sqrtAlphaHat_t = Algorithm.diffusionModel.sqrtAlphaHat(t);
        sqrtOneMinusAlphaHat_t = Algorithm.diffusionModel.sqrtOneMinusAlphaHat(t);
        
        xNoisy = sqrtAlphaHat_t .* x0 + sqrtOneMinusAlphaHat_t .* noise;
        
        % Predict noise (simplified neural network forward pass)
        predictedNoise = Algorithm.predictNoise(xNoisy, t, conditions);
        
        % Calculate loss
        loss = mean(sum((noise - predictedNoise).^2, 2));
        
        % Update model parameters (simplified gradient descent)
        learningRate = 0.001;
        gradient = (predictedNoise - noise)' * xNoisy / batchSize;
        Algorithm.diffusionModel.weights = Algorithm.diffusionModel.weights - learningRate * gradient;
    end
    
    function predictedNoise = predictNoise(Algorithm, x, t, conditions)
        % Simplified noise prediction (equivalent to neural network)
        predictedNoise = x * Algorithm.diffusionModel.weights + Algorithm.diffusionModel.bias;
        
        % Add conditioning information
        if ~isempty(conditions)
            % Simple conditioning: blend with condition-weighted prediction
            batchSize = size(x, 1);
            for i = 1:batchSize
                conditionWeight = mean(conditions(i, :));
                predictedNoise(i, :) = predictedNoise(i, :) * (1 + 0.1 * conditionWeight);
            end
        end
    end
    
    function Offspring = generateOffspring(Algorithm, Population, Problem, N, sampleSize, hybridRate, conditionType)
        % Generate offspring using hybrid strategy
        numDiffusionOffspring = round(hybridRate * N);
        numTraditionalOffspring = N - numDiffusionOffspring;
        
        Offspring = [];
        
        % Generate diffusion-based offspring
        if numDiffusionOffspring > 0 && Algorithm.generationCount > 1
            diffusionOffspring = Algorithm.generateDiffusionOffspring(Problem, numDiffusionOffspring, sampleSize, conditionType);
            Offspring = [Offspring; diffusionOffspring];
        end
        
        % Generate traditional offspring
        if numTraditionalOffspring > 0
            % Tournament selection for mating pool
            matingPool = TournamentSelection(2, numTraditionalOffspring, ones(length(Population), 1), zeros(length(Population), 1));
            
            % Apply genetic operators
            traditionalOffspring = OperatorGA(Problem, Population(matingPool));
            Offspring = [Offspring; traditionalOffspring];
        end
    end
    
    function offspring = generateDiffusionOffspring(Algorithm, Problem, numOffspring, sampleSize, conditionType)
        % Generate offspring using trained diffusion model
        if isempty(Algorithm.trainingData)
            % Fallback: generate random individuals
            offspring = Problem.Initialization(numOffspring);
            return;
        end
        
        % Sample from diffusion model
        samples = Algorithm.sampleFromDiffusion(numOffspring, sampleSize, conditionType);
        
        % Denormalize samples
        offspring = repmat(struct('decision', [], 'objs', [], 'cons', []), numOffspring, 1);
        for i = 1:numOffspring
            offspring(i).decision = Algorithm.denormalize(samples(i, :), Algorithm.scaler);
            offspring(i).decision = max(offspring(i).decision, Problem.lower);
            offspring(i).decision = min(offspring(i).decision, Problem.upper);
        end
        
        % Evaluate offspring
        offspring = Problem.Evaluation(offspring);
    end
    
    function samples = sampleFromDiffusion(Algorithm, numSamples, sampleSize, conditionType)
        % Sample from trained diffusion model (reverse process)
        samples = zeros(numSamples, length(Algorithm.scaler.lower));
        
        for s = 1:numSamples
            % Start from pure noise
            x = randn(1, length(Algorithm.scaler.lower));
            
            % Reverse diffusion process
            for t = length(Algorithm.noiseSchedule):-1:1
                % Predict noise
                predictedNoise = Algorithm.predictNoise(x, t, []);
                
                % Denoising step
                beta_t = Algorithm.noiseSchedule(t);
                sqrtOneMinusAlphaHat_t = Algorithm.diffusionModel.sqrtOneMinusAlphaHat(t);
                sqrtRecipAlpha_t = sqrt(1.0 / Algorithm.diffusionModel.alpha(t));
                
                % Calculate model mean
                modelMean = sqrtRecipAlpha_t * (x - beta_t * predictedNoise / sqrtOneMinusAlphaHat_t);
                
                if t == 1
                    x = modelMean;
                else
                    % Add sampling noise
                    posteriorVariance_t = Algorithm.diffusionModel.posteriorVariance(t);
                    noise = sqrt(posteriorVariance_t) * randn(size(x));
                    x = modelMean + noise;
                end
            end
            
            samples(s, :) = x;
        end
    end
    
    function updateTrainingData(Algorithm, Population, Problem)
        % Update training data with current best individuals
        if length(Population) > 0
            % Select best individuals for conditional generation
            [~, frontNo] = EnvironmentalSelection(Population, length(Population));
            bestIdx = find(frontNo == 1);
            
            if length(bestIdx) > 0
                Algorithm.bestIndividuals = Population(bestIdx);
            end
        end
    end
    
    function normalized = normalize(Algorithm, x, scaler)
        % Normalize data to [0, 1] range
        normalized = (x - scaler.lower) ./ scaler.range;
    end
    
    function denormalized = denormalize(Algorithm, x, scaler)
        % Denormalize data from [0, 1] range
        denormalized = x .* scaler.range + scaler.lower;
    end
    
    function Population = environmentalSelection(Algorithm, combinedPop, N, Problem)
        % Environmental selection for next generation
        [Population, ~, ~] = EnvironmentalSelection(combinedPop, N);
    end
end

end