%% Default Configuration for DiffusionEvolution Algorithm
% This configuration file contains default parameters for the DiffusionEvolution algorithm
%
% Parameters:
%   N               - Population size (default: 100)
%   diffusion_steps - Number of diffusion steps (default: 1000)
%   sample_size     - Number of samples generated by diffusion per generation (default: 50)
%   hybrid_rate     - Proportion of diffusion-generated offspring (default: 0.3)
%   model_type      - Type of diffusion model ('DDPM' or 'DDIM') (default: 'DDPM')
%   training_epochs - Epochs for training diffusion model per generation (default: 10)
%   noise_schedule  - Noise schedule type ('linear' or 'cosine') (default: 'linear')
%   condition_type  - Condition type for diffusion ('none', 'fitness', 'rank') (default: 'fitness')

%% Algorithm Parameters
params.N = 100;                          % Population size
params.diffusion_steps = 1000;           % Number of diffusion steps
params.sample_size = 50;                 % Samples per generation
params.hybrid_rate = 0.3;                % Diffusion offspring proportion
params.model_type = 'DDPM';              % Diffusion model type
params.training_epochs = 10;             % Training epochs per generation
params.noise_schedule = 'linear';        % Noise schedule type
params.condition_type = 'fitness';       % Condition type

%% Advanced Parameters
params.adaptive_diffusion = true;        % Enable adaptive diffusion strength
params.memory_size = 1000;               % Maximum training data size
params.diffusion_strength = 0.1;         % Base diffusion strength
params.min_hybrid_rate = 0.1;            % Minimum hybrid rate
params.max_hybrid_rate = 0.5;            % Maximum hybrid rate

%% Display configuration
fprintf('DiffusionEvolution Configuration:\n');
fprintf('Population Size: %d\n', params.N);
fprintf('Diffusion Steps: %d\n', params.diffusion_steps);
fprintf('Sample Size: %d\n', params.sample_size);
fprintf('Hybrid Rate: %.2f\n', params.hybrid_rate);
fprintf('Model Type: %s\n', params.model_type);
fprintf('Training Epochs: %d\n', params.training_epochs);
fprintf('Noise Schedule: %s\n', params.noise_schedule);
fprintf('Condition Type: %s\n', params.condition_type);

end