classdef AdaptiveScheduler < handle
% AdaptiveScheduler - Adaptive scheduler for GA/DM offspring ratio
%
% This class dynamically adjusts the ratio of offspring generated by
% the diffusion model vs genetic algorithm based on performance.

    properties(Access = private)
        BaseDMRatio     % Base ratio for DM offspring
        MinDMRatio      % Minimum DM ratio
        MaxDMRatio      % Maximum DM ratio
        WindowSize      % Window size for performance tracking
        DMHistory       % History of DM performance
        GAHistory       % History of GA performance
        StagnationCount % Count of stagnation generations
        LastBest        % Last best objective value
    end

    methods
        %% Constructor
        function obj = AdaptiveScheduler(base_ratio, min_ratio, max_ratio)
            obj.BaseDMRatio = base_ratio;
            obj.MinDMRatio = min_ratio;
            obj.MaxDMRatio = max_ratio;
            obj.WindowSize = 10;
            obj.DMHistory = [];
            obj.GAHistory = [];
            obj.StagnationCount = 0;
            obj.LastBest = inf;
        end
        
        %% Get DM offspring count
        function count = getDMOffspringCount(obj, total_offspring, dm_stats)
            % Calculate current DM ratio based on performance
            current_ratio = obj.calculateDMRatio(dm_stats);
            
            % Calculate count
            count = round(total_offspring * current_ratio);
            
            % Ensure at least some GA offspring
            if count >= total_offspring
                count = total_offspring - 1;
            end
            
            % Ensure non-negative
            count = max(0, count);
        end
        
        %% Calculate current DM ratio
        function ratio = calculateDMRatio(obj, dm_stats)
            % Start with base ratio
            ratio = obj.BaseDMRatio;
            
            % Adjust based on DM performance history
            if ~isempty(dm_stats.history) && length(dm_stats.history) >= 3
                recent_performance = mean(dm_stats.history(end-2:end));
                
                % If DM is performing well, increase its ratio
                if recent_performance > 0.3  % More than 30% survival rate
                    ratio = ratio * 1.2;
                elseif recent_performance < 0.1  % Less than 10% survival rate
                    ratio = ratio * 0.8;
                end
            end
            
            % Adjust based on stagnation
            if obj.StagnationCount > 5
                % Reduce DM ratio if stagnating
                ratio = ratio * 0.9;
            end
            
            % Clamp to valid range
            ratio = max(obj.MinDMRatio / 100, min(obj.MaxDMRatio / 100, ratio));
        end
        
        %% Update performance tracking
        function updatePerformance(obj, population, generation)
            % Track best objective value
            current_best = min(population.objs(:, 1));  % Assuming minimization
            
            if current_best >= obj.LastBest
                obj.StagnationCount = obj.StagnationCount + 1;
            else
                obj.StagnationCount = 0;
            end
            
            obj.LastBest = min(obj.LastBest, current_best);
        end
        
        %% Reset stagnation counter
        function resetStagnation(obj)
            obj.StagnationCount = 0;
        end
        
        %% Get stagnation count
        function count = getStagnationCount(obj)
            count = obj.StagnationCount;
        end
        
        %% Set base ratio
        function setBaseRatio(obj, ratio)
            obj.BaseDMRatio = ratio;
        end
        
        %% Get current statistics
        function stats = getStats(obj)
            stats = struct('base_ratio', obj.BaseDMRatio, ...
                          'stagnation_count', obj.StagnationCount, ...
                          'dm_history_length', length(obj.DMHistory));
        end
    end
end
